replicaCount: 1

image:
  name: ""

containerPort: 8000

service:
  targetPort: 8080

env:
  - name: DEBUG
    value: "false"
  - name: ALLOWED_HOSTS
    value: forum.philosofriends.com
  - name: CSRF_TRUSTED_ORIGINS
    value: https://forum.philosofriends.com,http://forum.philosofriends.com
  - name: POSTGRES_HOST
    value: postgres-postgresql.default.svc.cluster.local
  - name: POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_DB
    value: philonet
  - name: POSTGRES_USER
    value: philonet
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: forum-postgres
        key: POSTGRES_PASSWORD
  - name: PASSWORD_HASHER_ITERATIONS
    value: "260000"

command:
  - /app/entrypoint.sh
args:
  - uvicorn
  - philonet.asgi:application
  - --host
  - 0.0.0.0
  - --port
  - "8000"

persistence:
  enabled: false

nginx:
  enabled: true
  port: 8080
  staticMountPath: /usr/share/nginx/html/static
  config: |
    server {
      listen 8080;
      location /static/ {
        alias /usr/share/nginx/html/static/;
        access_log off;
        expires 1h;
      }
      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
