replicaCount: 1

image:
  name: ""

containerPort: 8000

env:
  - name: DATABASE_PATH
    value: /data/db.sqlite3
  - name: ALLOWED_HOSTS
    value: philo-news.nomaitech.com
  - name: CSRF_TRUSTED_ORIGINS
    value: https://philo-news.nomaitech.com,http://philo-news.nomaitech.com

persistence:
  enabled: true
  mountPath: /data
  size: 1Gi
